const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { loadState, saveState, mode: persistenceMode } = require('./lib/persistence');

const ROOT = __dirname;
const PUBLIC = path.join(ROOT, 'public');
const PORT = process.env.PORT || 4173;
const AI_API_KEY = process.env.OPENAI_API_KEY || '';
const AI_BASE_URL = (process.env.OPENAI_BASE_URL || 'https://api.openai.com/v1').replace(/\/$/, '');
const AI_MODEL = process.env.OPENAI_MODEL || 'gpt-5-mini';

const id = p => `${p}_${crypto.randomBytes(5).toString('hex')}`;
const now = () => new Date().toISOString();
const json = (res, status, data) => { const out = JSON.stringify(data); res.writeHead(status, {'Content-Type':'application/json','Content-Length':Buffer.byteLength(out)}); res.end(out); };
const body = req => new Promise((resolve,reject)=>{ let b=''; req.on('data',c=>{b+=c;if(b.length>2_000_000) req.destroy();}); req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}}); });
function log(db,text,type='system'){ db.activity ||= []; db.activity.unshift({time:now().slice(0,16).replace('T',' '),text,type}); db.activity=db.activity.slice(0,200); }
function trace(db,event,payload={}){ db.traces ||= []; db.traces.unshift({id:id('trace'),time:now(),event,payload}); db.traces=db.traces.slice(0,1000); }
function ensureCollections(db){ for(const k of ['leads','customers','offers','orders','payments','events','traces','activity']) db[k] ||= []; }
function context(db){ return JSON.stringify({company:db.company,agents:db.agents,projects:db.projects,tasks:db.tasks,approvals:db.approvals,revenue:db.revenue,leads:db.leads,customers:db.customers,offers:db.offers,orders:db.orders,payments:db.payments}); }
async function model(messages){
  if(!AI_API_KEY) return {ok:false,error:'OPENAI_API_KEY is not configured',mode:'local-fallback'};
  try { const r=await fetch(`${AI_BASE_URL}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${AI_API_KEY}`},body:JSON.stringify({model:AI_MODEL,messages,temperature:0.2})}); const data=await r.json(); if(!r.ok)return{ok:false,error:data?.error?.message||`Provider returned ${r.status}`,mode:'provider'}; return{ok:true,mode:'provider',text:data?.choices?.[0]?.message?.content||'',usage:data.usage||null}; } catch(e){return{ok:false,error:e.message,mode:'provider'};}
}
function tools(){ return [
 {id:'company_state',risk:'read',description:'Read company operating state.'}, {id:'task_create',risk:'write',description:'Create internal work.'}, {id:'agent_handoff',risk:'write',description:'Delegate work between agents.'}, {id:'approval_request',risk:'write',description:'Request founder approval for consequential actions.'}, {id:'lead_create',risk:'write',description:'Capture a sales lead.'}, {id:'offer_create',risk:'write',description:'Create a sellable offer.'}, {id:'order_create',risk:'write',description:'Create an order before payment.'}, {id:'payment_record',risk:'write',description:'Record a verified payment event only.'}, {id:'revenue_record',risk:'write',description:'Record revenue only from a verified payment.'}, {id:'trace_log',risk:'write',description:'Record execution telemetry.'}
]; }
function policy(db,action){ const spend=Number(action.spend||0), max=Number(db.company.maxSpend||0); if(spend>max)return{allowed:false,requiresApproval:true,reason:`Spend ₹${spend.toLocaleString('en-IN')} exceeds autonomous limit ₹${max.toLocaleString('en-IN')}.`}; if(action.external)return{allowed:false,requiresApproval:true,reason:'External side effects require founder approval in co-pilot mode.'}; return{allowed:true,requiresApproval:false}; }
function localPlan(goal){ const g=goal.toLowerCase(); if(/sell|revenue|customer|order|lead/.test(g))return[['Define offer, ICP and pricing','ceo','high'],['Build lead acquisition experiment','growth','high'],['Design qualification and follow-up workflow','sales','high'],['Build conversion asset','builder','medium']]; return[['Translate outcome into measurable milestones','ceo','high'],['Research highest-leverage growth experiments','growth','high'],['Design operating workflow','sales','medium'],['Build first usable implementation slice','builder','high']]; }
async function plan(db,goal){ if(!AI_API_KEY)return{mode:'local-fallback',tasks:localPlan(goal).map(([title,agent,priority])=>({title,agent,priority}))}; const r=await model([{role:'system',content:`You are TITAN COO. Return ONLY a JSON array of 3-6 executable internal tasks. Agents allowed: ceo,growth,sales,builder. Schema: {title,agent,priority}. No external claims. State: ${context(db)}`},{role:'user',content:goal}]); if(!r.ok)return{mode:'local-fallback',warning:r.error,tasks:localPlan(goal).map(([title,agent,priority])=>({title,agent,priority}))}; try{const x=JSON.parse(r.text.replace(/^```json\s*/,'').replace(/\s*```$/,'').trim()).filter(t=>t?.title&&['ceo','growth','sales','builder'].includes(t.agent)).slice(0,6);if(!x.length)throw Error('No valid tasks');return{mode:'provider',tasks:x,usage:r.usage};}catch(e){return{mode:'local-fallback',warning:`Planner JSON invalid: ${e.message}`,tasks:localPlan(goal).map(([title,agent,priority])=>({title,agent,priority}))};}
function verifiedPayment(db,p){return p.verified===true&&Number(p.amount)>0&&!!p.provider&&!!p.providerEventId;}
function recordPayment(db,b){ if(!verifiedPayment(db,b))return{error:'Payment must be verified and include amount, provider and providerEventId.',status:400}; if(db.payments.some(p=>p.provider===b.provider&&p.providerEventId===b.providerEventId))return{error:'Duplicate payment event ignored.',status:200,duplicate:true}; const payment={id:id('pay'),orderId:b.orderId||null,provider:b.provider,providerEventId:b.providerEventId,amount:Number(b.amount),currency:b.currency||'INR',verified:true,receivedAt:now()}; db.payments.unshift(payment); db.revenue.unshift({id:id('r'),date:now().slice(0,10),source:`${b.provider} payment`,amount:payment.amount,paymentId:payment.id,orderId:payment.orderId,verified:true}); db.events.unshift({id:id('evt'),type:'payment.verified',aggregateId:payment.id,time:now(),data:payment}); trace(db,'payment.verified',payment); log(db,`Verified payment received: ₹${payment.amount.toLocaleString('en-IN')}.`); return{payment}; }
async function api(req,res){ let db=await loadState(); ensureCollections(db); const u=new URL(req.url,'http://titan.local'); const p=u.pathname; try{
 if(req.method==='GET'&&p==='/api/health')return json(res,200,{ok:true,service:'titan-ai-company',version:'0.5.0',persistence:persistenceMode(),ai:{configured:!!AI_API_KEY,model:AI_MODEL,baseUrl:AI_BASE_URL},productionReady:!!process.env.DATABASE_URL});
 if(req.method==='GET'&&p==='/api/state')return json(res,200,db); if(req.method==='GET'&&p==='/api/tools')return json(res,200,{tools:tools()}); if(req.method==='GET'&&p==='/api/traces')return json(res,200,{traces:db.traces});
 if(req.method==='POST'&&p==='/api/company'){const b=await body(req);db.company={...db.company,...b};log(db,'Founder updated company constitution.');await saveState(db);return json(res,200,db.company);}
 if(req.method==='POST'&&p==='/api/policy/check'){const b=await body(req),r=policy(db,b);trace(db,'policy.check',{action:b,result:r});await saveState(db);return json(res,200,r);}
 if(req.method==='POST'&&p==='/api/orchestrate'){const b=await body(req),goal=(b.goal||'').trim();if(!goal)return json(res,400,{error:'goal required'});const pl=await plan(db,goal),created=[];for(const s of pl.tasks){const t={id:id('t'),title:s.title,agent:s.agent,status:'todo',priority:s.priority||'medium',project:b.project||'p1',createdAt:now(),output:null,source:'orchestrator'};db.tasks.unshift(t);created.push(t);}trace(db,'orchestrator.plan',{goal,taskIds:created.map(x=>x.id),mode:pl.mode});log(db,`COO orchestrated ${created.length} tasks for: ${goal.slice(0,100)}.`,'ai');await saveState(db);return json(res,201,{goal,tasks:created,mode:pl.mode,warning:pl.warning||null});}
 if(req.method==='POST'&&p==='/api/tasks'){const b=await body(req),t={id:id('t'),title:b.title||'Untitled task',agent:b.agent||'ceo',status:'todo',priority:b.priority||'medium',project:b.project||'p1',createdAt:now(),output:null};db.tasks.unshift(t);log(db,`Task created: ${t.title}.`);await saveState(db);return json(res,201,t);}
 if(req.method==='POST'&&/^\/api\/tasks\/[^/]+\/execute$/.test(p)){const tid=p.split('/')[3],t=db.tasks.find(x=>x.id===tid);if(!t)return json(res,404,{error:'Task not found'});const a=db.agents.find(x=>x.id===t.agent)||db.agents.find(x=>x.id==='ceo');t.status='working';if(a)a.status='working';trace(db,'task.start',{taskId:t.id,agent:t.agent});await saveState(db);const r=await model([{role:'system',content:`You are ${a?.name||'Alex'}, ${a?.role||'AI CEO'} in TITAN. Produce a concrete work product. Never claim external actions. State: ${context(db)}`},{role:'user',content:`Execute now: ${t.title}. Return result, assumptions/decisions, next action.`}]);t.output=r.ok?r.text:`Fallback execution: break "${t.title}" into a concrete checklist, deliverable and next measurable action.`;t.status='done';if(a)a.status='online';trace(db,'task.complete',{taskId:t.id,agent:t.agent,mode:r.ok?'provider':'local-fallback'});log(db,`${a?.name||'Agent'} completed: ${t.title}.`,'ai');await saveState(db);return json(res,200,{task:t,mode:r.ok?'provider':'local-fallback',warning:r.ok?null:r.error,usage:r.usage||null});}
 if(req.method==='POST'&&p==='/api/leads'){const b=await body(req),lead={id:id('lead'),name:b.name||'Unknown',email:b.email||null,source:b.source||'unknown',status:b.status||'new',notes:b.notes||'',createdAt:now(),updatedAt:now()};db.leads.unshift(lead);db.events.unshift({id:id('evt'),type:'lead.created',aggregateId:lead.id,time:now(),data:lead});await saveState(db);return json(res,201,lead);}
 if(req.method==='PATCH'&&/^\/api\/leads\/[^/]+$/.test(p)){const b=await body(req),lead=db.leads.find(x=>x.id===p.split('/')[3]);if(!lead)return json(res,404,{error:'Lead not found'});Object.assign(lead,b,{updatedAt:now()});await saveState(db);return json(res,200,lead);}
 if(req.method==='POST'&&p==='/api/offers'){const b=await body(req),offer={id:id('offer'),name:b.name||'Untitled offer',description:b.description||'',price:Number(b.price)||0,currency:b.currency||'INR',active:b.active!==false,createdAt:now()};db.offers.unshift(offer);await saveState(db);return json(res,201,offer);}
 if(req.method==='POST'&&p==='/api/orders'){const b=await body(req),offer=db.offers.find(x=>x.id===b.offerId);if(!offer)return json(res,404,{error:'Offer not found'});const order={id:id('ord'),offerId:offer.id,leadId:b.leadId||null,customerId:b.customerId||null,amount:Number(b.amount??offer.price),currency:b.currency||offer.currency,status:'pending_payment',createdAt:now()};db.orders.unshift(order);db.events.unshift({id:id('evt'),type:'order.created',aggregateId:order.id,time:now(),data:order});await saveState(db);return json(res,201,order);}
 if(req.method==='POST'&&p==='/api/payments'){const b=await body(req),r=recordPayment(db,b);if(r.error)return json(res,r.status,{error:r.error});await saveState(db);return json(res,r.duplicate?200:201,r);}
 if(req.method==='POST'&&p==='/api/revenue')return json(res,400,{error:'Manual revenue entry is disabled. Revenue must originate from a verified payment event.'});
 if(req.method==='POST'&&p==='/api/ceo'){const b=await body(req),q=(b.message||'').trim();if(!q)return json(res,400,{error:'message required'});const r=await model([{role:'system',content:`You are Alex, TITAN AI CEO. Be operational and truthful. Never claim external actions. State: ${context(db)}`},{role:'user',content:q}]);log(db,`Founder asked CEO: “${q.slice(0,100)}”.`,r.ok?'ai':'local');await saveState(db);return json(res,200,{reply:r.ok?r.text:'AI provider is not configured. The runtime is ready for provider execution.',mode:r.ok?'provider':'local-fallback',warning:r.ok?null:r.error,model:r.ok?AI_MODEL:null});}
 return json(res,404,{error:'Not found'});
 }catch(e){if(e.code==='STATE_CONFLICT')return json(res,409,{error:e.message,code:e.code});trace(db,'api.error',{path:p,error:e.message});try{await saveState(db);}catch(_){}return json(res,500,{error:e.message});}}
const handler=async(req,res)=>{if(req.url.startsWith('/api/'))return api(req,res);let file=req.url==='/'?'/index.html':req.url.split('?')[0];const fp=path.normalize(path.join(PUBLIC,file));if(!fp.startsWith(PUBLIC))return json(res,403,{error:'Forbidden'});fs.readFile(fp,(err,data)=>{if(err){res.writeHead(404);return res.end('Not found')}const ext=path.extname(fp);const types={'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.svg':'image/svg+xml'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});res.end(data);});};
if(require.main===module)http.createServer(handler).listen(PORT,()=>console.log(`TITAN v0.5 running at http://localhost:${PORT}`));
module.exports={handler,api,tools,policy,recordPayment};
